// Command reset сканирует пакеты модуля и генерирует методы Reset для
// структур, помеченных комментарием // generate:reset.
//
// Команда создает для каждого пакета файл reset.gen.go и описывает в нем
// логику очистки состояния структуры: примитивы приводятся к нулевым
// значениям, слайсы обрезаются до нулевой длины, map очищаются, а для
// вложенных структур и указателей используется рекурсивный сброс с вызовом
// метода Reset, если он доступен.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	// generateResetMarker — текст комментария, которым помечают структуру для
	// генерации метода Reset.
	generateResetMarker = "generate:reset"
	// generatedFileName — имя файла, в который записываются все сгенерированные
	// Reset-методы одного пакета.
	generatedFileName = "reset.gen.go"
	// generatedHeader помечает файл как сгенерированный этой утилитой и нужен
	// для безопасного удаления устаревших reset.gen.go.
	generatedHeader = "// Code generated by cmd/reset. DO NOT EDIT.\n"
)

// target описывает одну структуру, для которой нужно сгенерировать Reset.
// Здесь хранится имя типа, строка для receiver и типовая информация,
// необходимая при обходе полей.
type target struct {
	name         string
	receiverType string
	typ          types.Type
	structType   *types.Struct
}

// packageTarget группирует все найденные target внутри одного пакета. Это
// позволяет сгенерировать один общий reset.gen.go рядом с исходниками пакета.
type packageTarget struct {
	dir     string
	pkg     *packages.Package
	targets []target
}

// importSpec описывает один импорт, который потребуется в generated file.
// alias хранится отдельно, чтобы можно было разрешать конфликты имен пакетов.
type importSpec struct {
	alias string
	path  string
}

// importManager отслеживает уже использованные алиасы импортов и выдает
// стабильные имена для печати типов через go/types.
type importManager struct {
	pkgPath string
	byPath  map[string]string
	used    map[string]struct{}
}

// packageGenerator строит содержимое reset.gen.go для одного пакета: пишет
// методы Reset, собирает импорты и форматирует итоговый код.
type packageGenerator struct {
	pkg     *packages.Package
	targets []target
	imports *importManager
}

// main запускает основную логику генерации и завершает процесс с ненулевым
// кодом, если генератор не смог отработать успешно.
func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// run связывает все этапы генерации в один pipeline: поиск корня модуля,
// загрузка пакетов, сбор целевых структур, запись reset.gen.go и очистка
// устаревших generated files.
func run() error {
	root, err := findModuleRoot()
	if err != nil {
		return err
	}

	pkgs, err := loadPackages(root)
	if err != nil {
		return err
	}

	packagesWithTargets, packageDirs, err := collectTargets(pkgs)
	if err != nil {
		return err
	}

	generatedDirs := make(map[string]struct{}, len(packagesWithTargets))
	for _, pkgTarget := range packagesWithTargets {
		src, err := newPackageGenerator(pkgTarget.pkg, pkgTarget.targets).generate()
		if err != nil {
			return err
		}

		path := filepath.Join(pkgTarget.dir, generatedFileName)
		if err := writeIfChanged(path, src); err != nil {
			return err
		}
		generatedDirs[pkgTarget.dir] = struct{}{}
	}

	return cleanupGeneratedFiles(packageDirs, generatedDirs)
}

// findModuleRoot поднимается вверх от текущей директории до первого go.mod.
// Благодаря этому команду можно запускать не только строго из корня проекта,
// но и из вложенной папки модуля.
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod not found")
		}
		dir = parent
	}
}

// loadPackages загружает все пакеты модуля через go/packages вместе с AST и
// типовой информацией. AST нужен для чтения комментариев, а go/types — для
// понимания реальных типов полей при генерации Reset.
func loadPackages(root string) ([]*packages.Package, error) {
	cfg := &packages.Config{
		Dir: root,
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, fmt.Errorf("load packages: %w", err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		return nil, errors.New("failed to load packages")
	}

	return pkgs, nil
}

// collectTargets обходит все загруженные пакеты, собирает структуры с
// маркером // generate:reset и группирует их по директориям пакетов.
// Дополнительно функция возвращает список директорий всех пакетов, чтобы
// позднее можно было удалить неактуальные reset.gen.go.
func collectTargets(pkgs []*packages.Package) ([]packageTarget, map[string]struct{}, error) {
	packageDirs := make(map[string]struct{}, len(pkgs))
	result := make([]packageTarget, 0)

	for _, pkg := range pkgs {
		dir := packageDir(pkg)
		if dir == "" {
			continue
		}
		packageDirs[dir] = struct{}{}

		targets, err := findPackageTargets(pkg)
		if err != nil {
			return nil, nil, err
		}
		if len(targets) == 0 {
			continue
		}

		sort.Slice(targets, func(i, j int) bool {
			return targets[i].name < targets[j].name
		})
		result = append(result, packageTarget{
			dir:     dir,
			pkg:     pkg,
			targets: targets,
		})
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].dir < result[j].dir
	})

	return result, packageDirs, nil
}

// packageDir определяет директорию пакета по одному из его Go-файлов. В эту
// директорию потом записывается reset.gen.go.
func packageDir(pkg *packages.Package) string {
	files := pkg.CompiledGoFiles
	if len(files) == 0 {
		files = pkg.GoFiles
	}
	if len(files) == 0 {
		return ""
	}

	return filepath.Dir(files[0])
}

// findPackageTargets находит внутри одного пакета все структуры, помеченные
// generate:reset, и преобразует их к внутреннему описанию target.
// Для комментариев используется AST, а для анализа полей — go/types.
func findPackageTargets(pkg *packages.Package) ([]target, error) {
	targets := make([]target, 0)

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if !hasGenerateResetComment(genDecl, typeSpec) {
					continue
				}
				if _, ok := typeSpec.Type.(*ast.StructType); !ok {
					continue
				}

				typeName, ok := pkg.TypesInfo.Defs[typeSpec.Name].(*types.TypeName)
				if !ok {
					return nil, fmt.Errorf("type info not found for %s in %s", typeSpec.Name.Name, pkg.PkgPath)
				}

				typ := typeName.Type()
				structType, ok := types.Unalias(typ).Underlying().(*types.Struct)
				if !ok {
					continue
				}

				targets = append(targets, target{
					name:         typeSpec.Name.Name,
					receiverType: receiverType(typeSpec),
					typ:          typ,
					structType:   structType,
				})
			}
		}
	}

	return targets, nil
}

// hasGenerateResetComment определяет, относится ли маркер generate:reset к
// данной структуре. Для одиночного type declaration учитывается комментарий
// как на TypeSpec, так и на GenDecl; для grouped declaration — только на
// конкретном TypeSpec.
func hasGenerateResetComment(genDecl *ast.GenDecl, typeSpec *ast.TypeSpec) bool {
	if commentGroupHasMarker(typeSpec.Doc) {
		return true
	}
	if genDecl.Lparen.IsValid() {
		return false
	}

	return commentGroupHasMarker(genDecl.Doc)
}

// commentGroupHasMarker проверяет, содержит ли группа комментариев точную
// строку generate:reset. Поддерживаются и line comments, и block comments.
func commentGroupHasMarker(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}

	for _, comment := range group.List {
		text := strings.TrimSpace(comment.Text)
		text = strings.TrimPrefix(text, "//")
		text = strings.TrimPrefix(text, "/*")
		text = strings.TrimSuffix(text, "*/")
		for _, line := range strings.Split(text, "\n") {
			line = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "*"))
			if line == generateResetMarker {
				return true
			}
		}
	}

	return false
}

// receiverType строит строку receiver для сигнатуры Reset. Отдельная функция
// нужна для корректной печати generic-типов, например MyType[T].
func receiverType(typeSpec *ast.TypeSpec) string {
	if typeSpec.TypeParams == nil || len(typeSpec.TypeParams.List) == 0 {
		return typeSpec.Name.Name
	}

	names := make([]string, 0)
	for _, field := range typeSpec.TypeParams.List {
		for _, name := range field.Names {
			names = append(names, name.Name)
		}
	}

	if len(names) == 0 {
		return typeSpec.Name.Name
	}

	return fmt.Sprintf("%s[%s]", typeSpec.Name.Name, strings.Join(names, ", "))
}

// newPackageGenerator создает генератор для одного пакета и подготавливает
// менеджер импортов, который будет использоваться при печати типов.
func newPackageGenerator(pkg *packages.Package, targets []target) *packageGenerator {
	return &packageGenerator{
		pkg:     pkg,
		targets: targets,
		imports: newImportManager(pkg.PkgPath),
	}
}

// newImportManager инициализирует хранилище алиасов импортов. Оно гарантирует,
// что generated file не получит конфликтующие имена пакетов.
func newImportManager(pkgPath string) *importManager {
	return &importManager{
		pkgPath: pkgPath,
		byPath:  make(map[string]string),
		used:    make(map[string]struct{}),
	}
}

// qualifier возвращает алиас, под которым внешний пакет должен быть
// импортирован в generated file. Для текущего пакета алиас не нужен.
func (m *importManager) qualifier(pkg *types.Package) string {
	if pkg == nil || pkg.Path() == m.pkgPath {
		return ""
	}

	if alias, ok := m.byPath[pkg.Path()]; ok {
		return alias
	}

	base := pkg.Name()
	if base == "" {
		base = "pkg"
	}
	if token.Lookup(base).IsKeyword() {
		base += "pkg"
	}

	alias := base
	for idx := 1; ; idx++ {
		if _, exists := m.used[alias]; !exists {
			break
		}
		alias = fmt.Sprintf("%s%d", base, idx)
	}

	m.byPath[pkg.Path()] = alias
	m.used[alias] = struct{}{}
	return alias
}

// specs возвращает отсортированный список импортов для записи в файл. Это
// делает результат генерации стабильным и предсказуемым в diff.
func (m *importManager) specs() []importSpec {
	specs := make([]importSpec, 0, len(m.byPath))
	for path, alias := range m.byPath {
		specs = append(specs, importSpec{
			alias: alias,
			path:  path,
		})
	}

	sort.Slice(specs, func(i, j int) bool {
		return specs[i].path < specs[j].path
	})

	return specs
}

// generate собирает полный исходный текст reset.gen.go для пакета: сначала
// методы Reset, затем раздел imports, после чего форматирует код стандартным
// gofmt-совместимым formatter.
func (g *packageGenerator) generate() ([]byte, error) {
	var body bytes.Buffer
	for idx, target := range g.targets {
		if idx > 0 {
			body.WriteByte('\n')
		}
		g.writeMethod(&body, target)
	}

	var src bytes.Buffer
	src.WriteString(generatedHeader)
	fmt.Fprintf(&src, "package %s\n\n", g.pkg.Name)

	if specs := g.imports.specs(); len(specs) > 0 {
		src.WriteString("import (\n")
		for _, spec := range specs {
			fmt.Fprintf(&src, "\t%s %q\n", spec.alias, spec.path)
		}
		src.WriteString(")\n\n")
	}

	src.Write(body.Bytes())

	formatted, err := format.Source(src.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated file for %s: %w", g.pkg.PkgPath, err)
	}

	return formatted, nil
}

// writeMethod генерирует один метод Reset для конкретной структуры.
// Метод всегда начинается с проверки receiver на nil, после чего добавляется
// код очистки для каждого поля структуры.
func (g *packageGenerator) writeMethod(buf *bytes.Buffer, target target) {
	fmt.Fprintf(buf, "func (r *%s) Reset() {\n", target.receiverType)
	buf.WriteString("\tif r == nil {\n")
	buf.WriteString("\t\treturn\n")
	buf.WriteString("\t}\n")

	if target.structType.NumFields() > 0 {
		buf.WriteByte('\n')
	}

	seen := extendSeen(nil, typeKey(target.typ))
	for idx := 0; idx < target.structType.NumFields(); idx++ {
		field := target.structType.Field(idx)
		if field.Name() == "_" {
			continue
		}
		g.emitReset(buf, "\t", "r."+field.Name(), field.Type(), seen)
	}

	buf.WriteString("}\n")
}

// emitReset — центральная точка генерации логики сброса. Она определяет вид
// типа поля и выбирает нужное правило: нулевое значение, обрезка slice,
// очистка map, рекурсивный сброс pointer/struct и так далее.
func (g *packageGenerator) emitReset(buf *bytes.Buffer, indent, expr string, typ types.Type, seen map[types.Type]struct{}) {
	resolved := types.Unalias(typ)
	if _, ok := resolved.(*types.TypeParam); ok {
		g.writeLine(buf, indent, "%s = %s", expr, g.zeroValueExpr(typ))
		return
	}

	switch underlying := resolved.Underlying().(type) {
	case *types.Basic:
		g.writeLine(buf, indent, "%s = %s", expr, zeroBasicValue(underlying))
	case *types.Slice:
		g.writeLine(buf, indent, "%s = %s[:0]", expr, expr)
	case *types.Map:
		g.writeLine(buf, indent, "clear(%s)", expr)
	case *types.Pointer:
		g.emitPointerReset(buf, indent, expr, underlying.Elem(), seen)
	case *types.Struct:
		g.emitStructReset(buf, indent, expr, typ, underlying, seen)
	case *types.Interface, *types.Signature, *types.Chan:
		g.writeLine(buf, indent, "%s = nil", expr)
	default:
		g.writeLine(buf, indent, "%s = %s", expr, g.zeroValueExpr(typ))
	}
}

// emitPointerReset генерирует код сброса для ненулевого указателя. Сначала он
// пытается вызвать Reset у pointed value через interface check, а если такого
// метода нет, рекурсивно сбрасывает разыменованное значение по общим правилам.
func (g *packageGenerator) emitPointerReset(
	buf *bytes.Buffer,
	indent string,
	expr string,
	elem types.Type,
	seen map[types.Type]struct{},
) {
	g.writeLine(buf, indent, "if %s != nil {", expr)
	inner := indent + "\t"
	g.writeLine(buf, inner, "if resetter, ok := any(%s).(interface{ Reset() }); ok {", expr)
	g.writeLine(buf, inner+"\t", "resetter.Reset()")
	g.writeLine(buf, inner, "} else {")
	g.emitResetFallback(buf, inner+"\t", derefExpr(expr), elem, seen)
	g.writeLine(buf, inner, "}")
	g.writeLine(buf, indent, "}")
}

// emitStructReset обрабатывает значение-структуру. Если у адреса структуры
// есть метод Reset, приоритетно вызывается он; иначе сброс разворачивается по
// полям через emitStructFallback.
func (g *packageGenerator) emitStructReset(
	buf *bytes.Buffer,
	indent string,
	expr string,
	typ types.Type,
	structType *types.Struct,
	seen map[types.Type]struct{},
) {
	g.writeLine(buf, indent, "if resetter, ok := any(&%s).(interface{ Reset() }); ok {", expr)
	g.writeLine(buf, indent+"\t", "resetter.Reset()")
	g.writeLine(buf, indent, "} else {")
	g.emitStructFallback(buf, indent+"\t", expr, typ, structType, seen)
	g.writeLine(buf, indent, "}")
}

// emitResetFallback используется там, где уже выполнены внешние проверки,
// например nil-check для указателя, и нужно либо вручную развернуть структуру,
// либо вернуться к общей логике emitReset для остальных типов.
func (g *packageGenerator) emitResetFallback(
	buf *bytes.Buffer,
	indent string,
	expr string,
	typ types.Type,
	seen map[types.Type]struct{},
) {
	resolved := types.Unalias(typ)
	if _, ok := resolved.(*types.TypeParam); ok {
		g.writeLine(buf, indent, "%s = %s", expr, g.zeroValueExpr(typ))
		return
	}

	if structType, ok := resolved.Underlying().(*types.Struct); ok {
		g.emitStructFallback(buf, indent, expr, typ, structType, seen)
		return
	}

	g.emitReset(buf, indent, expr, typ, seen)
}

// emitStructFallback вручную генерирует очистку полей структуры, если
// собственного Reset у нее нет. seen защищает от бесконечной рекурсии на
// циклических типах, а canExpandStruct не допускает обращение к недоступным
// полям структур из других пакетов.
func (g *packageGenerator) emitStructFallback(
	buf *bytes.Buffer,
	indent string,
	expr string,
	typ types.Type,
	structType *types.Struct,
	seen map[types.Type]struct{},
) {
	if structType.NumFields() == 0 || !g.canExpandStruct(structType) || seenType(seen, typ) {
		g.writeLine(buf, indent, "%s = %s", expr, g.zeroValueExpr(typ))
		return
	}

	nextSeen := extendSeen(seen, typeKey(typ))
	for idx := 0; idx < structType.NumFields(); idx++ {
		field := structType.Field(idx)
		if field.Name() == "_" {
			continue
		}
		g.emitReset(buf, indent, expr+"."+field.Name(), field.Type(), nextSeen)
	}
}

// canExpandStruct проверяет, безопасно ли разворачивать структуру по полям в
// generated code. Если структура из другого пакета содержит неэкспортные
// поля, такой код не скомпилируется, поэтому в этом случае нужен fallback к
// полному нулевому значению.
func (g *packageGenerator) canExpandStruct(structType *types.Struct) bool {
	for idx := 0; idx < structType.NumFields(); idx++ {
		field := structType.Field(idx)
		if field.Name() == "_" {
			continue
		}
		if field.Exported() {
			continue
		}
		if field.Pkg() == nil || field.Pkg() == g.pkg.Types {
			continue
		}
		return false
	}

	return true
}

// zeroValueExpr строит универсальное выражение нулевого значения для любого
// типа. Форма *new(T) работает и для именованных, и для составных типов.
func (g *packageGenerator) zeroValueExpr(typ types.Type) string {
	return fmt.Sprintf("*new(%s)", g.typeString(typ))
}

// typeString печатает тип в синтаксисе Go и при необходимости подтягивает
// алиасы импортов через importManager.
func (g *packageGenerator) typeString(typ types.Type) string {
	return types.TypeString(typ, g.imports.qualifier)
}

// writeLine записывает одну строку generated code с нужным уровнем отступа.
// Это убирает повторяющийся fmt.Fprintf по всему генератору.
func (g *packageGenerator) writeLine(buf *bytes.Buffer, indent, format string, args ...any) {
	fmt.Fprintf(buf, indent+format+"\n", args...)
}

// zeroBasicValue возвращает литерал нулевого значения для базового типа Go.
// Он используется там, где можно сгенерировать более читаемое присваивание,
// чем общий fallback через *new(T).
func zeroBasicValue(basic *types.Basic) string {
	switch {
	case basic.Kind() == types.UnsafePointer:
		return "nil"
	case basic.Info()&types.IsBoolean != 0:
		return "false"
	case basic.Info()&types.IsString != 0:
		return `""`
	default:
		return "0"
	}
}

// typeKey нормализует тип перед помещением в seen. Это помогает одинаково
// трактовать alias и исходный тип при защите от циклических обходов.
func typeKey(typ types.Type) types.Type {
	return types.Unalias(typ)
}

// seenType проверяет, встречался ли текущий тип в этой ветке рекурсии.
// Если встречался, разворачивать структуру дальше нельзя, иначе можно уйти в
// бесконечную генерацию на self-referential типах.
func seenType(seen map[types.Type]struct{}, typ types.Type) bool {
	if len(seen) == 0 {
		return false
	}
	_, ok := seen[typeKey(typ)]
	return ok
}

// extendSeen создает новую карту посещенных типов для следующего уровня
// рекурсии. Копирование делает ветви генерации независимыми друг от друга.
func extendSeen(seen map[types.Type]struct{}, typ types.Type) map[types.Type]struct{} {
	next := make(map[types.Type]struct{}, len(seen)+1)
	for key := range seen {
		next[key] = struct{}{}
	}
	next[typeKey(typ)] = struct{}{}
	return next
}

// derefExpr строит строковое выражение разыменования указателя для вставки в
// generated code.
func derefExpr(expr string) string {
	return "(*" + expr + ")"
}

// writeIfChanged записывает generated file только если содержимое реально
// изменилось. Это избавляет от лишних перезаписей и ненужного шума в git.
func writeIfChanged(path string, src []byte) error {
	current, err := os.ReadFile(path)
	if err == nil && bytes.Equal(current, src) {
		return nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read %s: %w", path, err)
	}

	if err := os.WriteFile(path, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	return nil
}

// cleanupGeneratedFiles удаляет старые reset.gen.go из тех пакетов, где после
// очередного запуска генератора больше не осталось структур с generate:reset.
// Удаляются только файлы с ожидаемым generated header, чтобы не затронуть
// пользовательские файлы с таким же именем.
func cleanupGeneratedFiles(packageDirs, generatedDirs map[string]struct{}) error {
	for dir := range packageDirs {
		if _, ok := generatedDirs[dir]; ok {
			continue
		}

		path := filepath.Join(dir, generatedFileName)
		src, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		if !bytes.HasPrefix(src, []byte(generatedHeader)) {
			continue
		}
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove %s: %w", path, err)
		}
	}

	return nil
}
